language: php

php:
    - 5.6
    - 5.5
    - 5.4

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-dev --no-interaction

script: phpunit

before_deploy:
    - echo "phar.readonly = Off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -LSs https://box-project.github.io/box2/installer.php | php
    - php box.phar build

deploy:
    api_key: {{OAUTH_TOKEN}}
    provider: releases
    file: "change_ini_setting.phar"
    skip_cleanup: true

