language: php

php:
    - 5.6
    - 5.5
    - 5.4

before_script:
    - travis_retry composer self-update

script: phpunit

before_deploy:
    - curl -LSs https://box-project.github.io/box2/installer.php | php
    - box build

