#!/usr/bin/env php
<?php
use ChangeIniSetting\ChangeIniSetting;

$opts = getopt("", array("file:", "name:", "value:"));

$changer = new ChangeIniSetting($opts["file"]);
$changer->updateSetting($opts["name"], $opts["value"]);
?>