#!/usr/bin/env php
<?php
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
  if (file_exists($file)) {
    require $file;
    break;
  }
}

use ChangeIniSetting\ChangeIniSetting;

$opts = getopt("", array("file:", "name:", "value:"));

$changer = new ChangeIniSetting($opts["file"]);
$changer->updateSetting($opts["name"], $opts["value"]);
?>